; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Common settings for both environments
[platformio]
src_dir = main

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Client microcontroller environment  
[env:client]
build_flags = 
    -DCONFIG_CLIENT_MODE=1
; Windows Versions of Upload Port
upload_port = COM*
monitor_port = COM*
; MacOS Versions of Upload Port
; upload_port = /dev/cu.usbmodem101
; monitor_port = /dev/cu.usbmodem101

; Main microcontroller environment
[env:main]
build_flags = 
    -DCONFIG_MAIN_MODE=1
; Windows Versions of Upload Port
upload_port = COM*
monitor_port = COM*
; MacOS Versions of Upload Port
; upload_port = /dev/cu.usbmodem101
; monitor_port = /dev/cu.usbmodem101

upload_speed = 460800
upload_resetmethod = usb_reset
